version: 2

sources:
  - name: default
    # database: your_database_name  # Optional, depending on your warehouse
    schema: main
    tables:
      - name: raw_airlines
      - name: raw_flights
      - name: raw_destinations
      - name: raw_aircrafttypes

